init:
  plugins:
    - mocha
    - clean
    - packagejson
    - grab
settings:
  exec:
    env:
      # Required in Linux, harmless elsewhere, Position Independant Code is
      # enabled by default.
      CPPFLAGS: "-fPIC"
      CFLAGS: "-O3"
  # Url/version/extension of `xz` sources.
  # gz is the most common, but you can of course override it!
  xzWebUrl: 'http://tukaani.org/xz/xz'
  xzVersion: '5.2.2'
  xzExt: 'gz'
  # Clean all these paths/files
  clean:
    path: ['lib', '*.log']
    distclean: ['build', 'xz*.tar.*']
  srcPath: 'src'
  libPath: 'lib'
  coffee: './node_modules/.bin/coffee'
  npg: './node_modules/.bin/node-pre-gyp'
  cpu: 4
  mocha:
    useCoffee: true
clean:
  - '%npg% clean'
  - rm -rf %clean.path%
fetch_lzma:
  - log: Fetching source ...
  - grab: "%xzWebUrl%-%xzVersion%.tar.%xzExt%"
  - mkdir -p deps/xz
  - |-
    opts="xvf"
    if [ "%xzExt%" = "gz" ]
    then
      opts="z$opts"
    elif [ "%xzExt%" = "bz2" ]
    then
      opts="j$opts"
    elif [ "%xzExt%" = "xz" ]
    then
      opts="J$opts"
    else
      echo "Not understood: $opts"
    fi
    tar $opts xz-%xzVersion%.tar.%xzExt% -C deps/xz --strip-components=1
  - log: Done fetching source.
build_lzma:
  - log: Building LibLZMA from sources, using %cpu% threads ! (change by passing cpu=xxx)
  - log: Cleaning deps ...
  - rm -rf deps
  - task: fetch_lzma
  - cd deps/xz
  - ./autogen.sh
  - ./configure --prefix=`pwd` --enable-threads --enable-static --disable-shared --disable-scripts --disable-lzmainfo
    --disable-lzma-links --disable-lzmadec --disable-xzdec --disable-xz --disable-rpath
  - make -j%cpu%
  - make install
  - env: CPATH=`pwd`/include
  - env: LIBRARY_PATH=`pwd`/lib
  - env: LD_LIBRARY_PATH=$LIBRARY_PATH:$LD_LIBRARY_PATH
  - log: Done compiling liblzma. headers are at $CPATH
  - cd ../..
build_module:
  - log: Building %name% version %version% Add-On ...
  - '%npg% configure build'
install_module:
  - log: Installing %name% version %version% Add-On ...
  - '%npg% install --fallback-to-build'
build:
  # If we are compiling, we surely won't want to try to download a precompiled binary
  - |
    if [ "$COMPILE" = "1" ]
    then
      %ubs% build_lzma build_module xzVersion=%xzVersion% xzExt=%xzExt%
    else
      %ubs% install_module
    fi
  # If we do not have any js file, we build it
  - '[ -r %libPath%/lzma.js ] || %ubs% build_coffee'
build_coffee:
  - log: Building Javascript API...
  - '%coffee% -c -o %libPath% %srcPath%'
  - log: Done building Javascript.
test:
  - task: mocha-test
install:
  - task: build
  - log: Build done.
