packages:
  - "packages/*"

catalog:
  "@biomejs/biome": ^2.4.4
  "@types/node": ^25.3.2
  "@vitest/coverage-v8": ^4.0.18
  typescript: ^5.9.3
  vitest: ^4.0.18

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
