#!/usr/bin/env python3
"""Print a revision marker for checked-out native sources and control files.

Environment, dependency, and toolchain identity are intentionally outside this
marker.
"""

import argparse
import hashlib
import sys
from pathlib import Path

from native_sources import native_source_paths


REQUIRED_FILES = (
    "binding.gyp",
    "scripts/binding_config.py",
    "scripts/build_xz_with_cmake.py",
    "scripts/download_xz_from_github.py",
    "scripts/walk_sources.py",
    "scripts/copy_dll.py",
    "scripts/native_sources.py",
    "scripts/native_fingerprint.py",
    "xz-version.json",
)
CHUNK_SIZE = 64 * 1024


def fail(message):
    print(f"native_fingerprint.py: {message}", file=sys.stderr)
    raise SystemExit(1)


def add_path(digest, repo_root, path):
    digest.update(path.relative_to(repo_root).as_posix().encode("utf-8"))
    digest.update(b"\0")
    if not path.is_file():
        fail(f"required input is missing: {path}")
    try:
        with path.open("rb") as source:
            while chunk := source.read(CHUNK_SIZE):
                digest.update(chunk)
    except OSError as error:
        fail(f"could not read required input {path}: {error}")
    digest.update(b"\0")


def fingerprint(repo_root):
    digest = hashlib.sha256()
    for relative_path in native_source_paths(repo_root):
        add_path(digest, repo_root, repo_root / relative_path)

    for relative_path in REQUIRED_FILES:
        add_path(digest, repo_root, repo_root / relative_path)

    return digest.hexdigest()


def write_header(path, value):
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(
            "// Generated by scripts/native_fingerprint.py; do not edit.\n"
            f'#define NATIVE_FINGERPRINT "{value}"\n',
            encoding="utf-8",
        )
    except OSError as error:
        fail(f"could not write generated header {path}: {error}")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--header", type=Path)
    arguments = parser.parse_args()
    repo_root = Path(__file__).resolve().parent.parent
    bindings_dir = repo_root / "src" / "bindings"
    if not bindings_dir.is_dir():
        fail(f"required input directory is missing: {bindings_dir}")

    value = fingerprint(repo_root)
    if arguments.header:
        write_header(arguments.header, value)
    else:
        print(value)


if __name__ == "__main__":
    main()
