name: Check prerequisites

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      runtime_link:
        required: true
        type: string
    # Map the workflow outputs to job outputs
    outputs:
      has-mt:
        description: "Does the library exposes multithreading API ?"
        value: ${{ jobs.check.outputs.has-mt }}

jobs:
  check:
    name: Checking if system library is multi threading capable
    runs-on: ${{ inputs.os }}
    # Map the job outputs to step outputs
    outputs:
      has-mt: ${{ steps.check-mt.outputs.CONDITION }}
    steps:
      - name: Checking if system library is multi threading capable
        id: check-mt
        if: inputs.runtime_link == 'static'
        run: |
          if readelf -Wa /usr/lib/x86_64-linux-gnu/liblzma.a | grep lzma_stream_encoder_mt
          then
            echo "Static system library is multi threading capable: yes"
            echo '::set-output name=CONDITION::true'
          else
            echo "Static system library is multi threading capable: no"
            echo '::set-output name=CONDITION::false'
          fi
      - name: Checking if system library is multi threading capable
        id: check-mt
        if: inputs.runtime_link == 'shared'
        run: |
          if readelf -Wa /usr/lib/x86_64-linux-gnu/liblzma.so | grep lzma_stream_encoder_mt
          then
            echo "Dynamic system library is multi threading capable: yes"
            echo '::set-output name=CONDITION::true'
          else
            echo "Dynamic system library is multi threading capable: no"
            echo '::set-output name=CONDITION::false'
          fi
