name: Test on Linux
on:
  push:
    paths:
      - "**"
      - "!*.md"
      - "!.github"
      - ".github/workflows/ci-linux.yml"
    branches:
      - master
      - "releases/**"
    tags-ignore:
      - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:
    inputs:
      xz_version:
        description: 'XZ version (e.g., v5.8.1, v5.4.0, latest, or empty for default)'
        required: false
        type: string
  workflow_call:
    inputs:
      cache-prefix:
        description: 'Cache prefix for isolation'
        required: false
        type: string
        default: ''
      xz_version:
        description: 'XZ version to use'
        required: false
        type: string
        default: ''

permissions:
  contents: read
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: [18, 20, 22]
        runtime_link: [static, shared]
        use_global_liblzma: [true, false]
        enable_threads: [no]
    runs-on: ${{ matrix.os }}
    name: Node ${{ matrix.node }} / System Xz ? ${{ matrix.use_global_liblzma }} / Threading enabled ? ${{ matrix.enable_threads }} / Runtime is ${{ matrix.runtime_link }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Use node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          architecture: x64
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ inputs.cache-prefix }}${{ runner.os }}-ccache-${{ matrix.runtime_link }}-${{ matrix.enable_threads }}
          max-size: 500M
      - name: Setup pnpm store cache
        uses: actions/cache@v4
        with:
          path: ~/.local/share/pnpm/store
          key: ${{ inputs.cache-prefix }}${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Setup xz deps cache
        if: ${{ !matrix.use_global_liblzma }}
        uses: actions/cache@v4
        with:
          path: |
            deps/xz
            deps/xz.tar.gz
            build/liblzma
          key: ${{ inputs.cache-prefix }}${{ runner.os }}-xz-${{ matrix.runtime_link }}-${{ matrix.enable_threads }}-${{ inputs.xz_version || github.event.inputs.xz_version || 'default' }}-${{ hashFiles('scripts/download_xz_from_github.py', 'xz-version.json') }}
          restore-keys: |
            ${{ inputs.cache-prefix }}${{ runner.os }}-xz-${{ matrix.runtime_link }}-${{ matrix.enable_threads }}-
      - name: Install
        run: pnpm install --frozen-lockfile
        env:
          XZ_VERSION: ${{ inputs.xz_version || github.event.inputs.xz_version || '' }}
          USE_GLOBAL: ${{ matrix.use_global_liblzma }}
          RUNTIME_LINK: ${{ matrix.runtime_link }}
          ENABLE_THREAD_SUPPORT: ${{ matrix.enable_threads }}
          CC: ccache gcc
          CXX: ccache g++
      - name: Build
        run: pnpm run build
      - name: Lint
        if: ${{ matrix.node == '20' && matrix.runtime_link == 'static' && matrix.use_global_liblzma == false }}
        run: pnpm run check
      - name: Test
        run: pnpm test

  check:
    name: Checking if system library is multi threading capable
    runs-on: 'ubuntu-latest'
    # Map the job outputs to step outputs
    outputs:
      static-has-mt: ${{ steps.check-mt.outputs.STATIC }}
      shared-has-mt: ${{ steps.check-mt.outputs.SHARED }}
    steps:
      - name: Checking if system library is multi threading capable
        id: check-mt
        run: |
          if readelf -Wa /usr/lib/x86_64-linux-gnu/liblzma.a | grep lzma_stream_encoder_mt
          then
            echo "Static system library is multi threading capable: yes"
            echo "STATIC=true" >> $GITHUB_OUTPUT
          else
            echo "Static system library is multi threading capable: no"
            echo "STATIC=false" >> $GITHUB_OUTPUT
          fi
          if readelf -Wa /usr/lib/x86_64-linux-gnu/liblzma.so | grep lzma_stream_encoder_mt
          then
            echo "Dynamic system library is multi threading capable: yes"
            echo "SHARED=true" >> $GITHUB_OUTPUT
          else
            echo "Dynamic system library is multi threading capable: no"
            echo "SHARED=false" >> $GITHUB_OUTPUT
          fi

  test-mt:
    needs: check
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: [18, 20, 22]
        runtime_link: [static, shared]
        use_global_liblzma: [true, false]
        enable_threads: [yes]
    runs-on: ${{ matrix.os }}
    name: Node ${{ matrix.node }} / System Xz ? ${{ matrix.use_global_liblzma }} / Threading enabled ? ${{ matrix.enable_threads }} / Runtime is ${{ matrix.runtime_link }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Use node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          architecture: x64
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ inputs.cache-prefix }}${{ runner.os }}-ccache-${{ matrix.runtime_link }}-${{ matrix.enable_threads }}
          max-size: 500M
      - name: Setup pnpm store cache
        uses: actions/cache@v4
        with:
          path: ~/.local/share/pnpm/store
          key: ${{ inputs.cache-prefix }}${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Setup xz deps cache
        if: ${{ !matrix.use_global_liblzma }}
        uses: actions/cache@v4
        with:
          path: |
            deps/xz
            deps/xz.tar.gz
            build/liblzma
          key: ${{ inputs.cache-prefix }}${{ runner.os }}-xz-${{ matrix.runtime_link }}-${{ matrix.enable_threads }}-${{ inputs.xz_version || github.event.inputs.xz_version || 'default' }}-${{ hashFiles('scripts/download_xz_from_github.py', 'xz-version.json') }}
          restore-keys: |
            ${{ inputs.cache-prefix }}${{ runner.os }}-xz-${{ matrix.runtime_link }}-${{ matrix.enable_threads }}-
      - name: debug
        run: |
          echo use_global_liblzma: ${{ matrix.use_global_liblzma }}
          echo static-has-mt: ${{ needs.check.outputs.static-has-mt }}
          echo shared-has-mt: ${{ needs.check.outputs.shared-has-mt }}
      - name: Install
        if: ${{ !matrix.use_global_liblzma || (matrix.runtime_link == 'static' && needs.check.outputs.static-has-mt != 'false') || (matrix.runtime_link == 'shared' && needs.check.outputs.shared-has-mt != 'false') }}
        run: pnpm install --frozen-lockfile
        env:
          XZ_VERSION: ${{ inputs.xz_version || github.event.inputs.xz_version || '' }}
          USE_GLOBAL: ${{ matrix.use_global_liblzma }}
          RUNTIME_LINK: ${{ matrix.runtime_link }}
          ENABLE_THREAD_SUPPORT: ${{ matrix.enable_threads }}
          CC: ccache gcc
          CXX: ccache g++
      - name: Build
        if: ${{ !matrix.use_global_liblzma || (matrix.runtime_link == 'static' && needs.check.outputs.static-has-mt != 'false') || (matrix.runtime_link == 'shared' && needs.check.outputs.shared-has-mt != 'false') }}
        run: pnpm run build
      - name: Lint
        if: ${{ matrix.node == '20' && matrix.runtime_link == 'static' && matrix.use_global_liblzma == false && (!matrix.use_global_liblzma || (matrix.runtime_link == 'static' && needs.check.outputs.static-has-mt != 'false') || (matrix.runtime_link == 'shared' && needs.check.outputs.shared-has-mt != 'false')) }}
        run: pnpm run check
      - name: Test
        if: ${{ !matrix.use_global_liblzma || (matrix.runtime_link == 'static' && needs.check.outputs.static-has-mt != 'false') || (matrix.runtime_link == 'shared' && needs.check.outputs.shared-has-mt != 'false') }}
        run: pnpm test
