name: PR Smoke Tests
on:
  pull_request:
    branches:
      - master
      - "releases/**"

permissions:
  contents: read

jobs:
  smoke-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [20]
        runtime_link: [static]
        use_global_liblzma: [false]
        enable_threads: [no]
    runs-on: ${{ matrix.os }}
    name: Smoke test on ${{ matrix.os }} / Node ${{ matrix.node }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Use node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          architecture: x64
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml
      - name: Setup ccache (Linux/macOS)
        if: ${{ runner.os != 'Windows' }}
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: pr-${{ runner.os }}-ccache-${{ matrix.runtime_link }}-${{ matrix.enable_threads }}
          max-size: 200M
      - name: Setup pnpm store cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.local/share/pnpm/store
            ~/Library/pnpm/store
            ~\AppData\Local\pnpm\store
          key: pr-${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            pr-${{ runner.os }}-pnpm-store-
            ${{ runner.os }}-pnpm-store-
      - name: Setup xz deps cache
        uses: actions/cache@v4
        with:
          path: |
            deps/xz
            deps/xz.tar.xz
            build/liblzma
          key: pr-${{ runner.os }}-xz-${{ matrix.runtime_link }}-${{ matrix.enable_threads }}-${{ hashFiles('scripts/download_extract_deps.py') }}
          restore-keys: |
            pr-${{ runner.os }}-xz-${{ matrix.runtime_link }}-${{ matrix.enable_threads }}-
            ${{ runner.os }}-xz-${{ matrix.runtime_link }}-${{ matrix.enable_threads }}-
      - name: Install
        run: pnpm install --frozen-lockfile
        env:
          USE_GLOBAL: ${{ matrix.use_global_liblzma }}
          RUNTIME_LINK: ${{ matrix.runtime_link }}
          ENABLE_THREAD_SUPPORT: ${{ matrix.enable_threads }}
          CC: ${{ runner.os == 'Linux' && 'ccache gcc' || (runner.os == 'macOS' && 'ccache clang' || '') }}
          CXX: ${{ runner.os == 'Linux' && 'ccache g++' || (runner.os == 'macOS' && 'ccache clang++' || '') }}
      - name: Build
        run: pnpm run build
      - name: Lint
        run: pnpm run check
      - name: Test
        run: pnpm test
      - name: Type check
        run: pnpm run type-check