name: Test on Windows
on:
  push:
    paths:
      - "!*.md"
      - "!.github"
      - ".github/workflows/ci-windows.yml"
    branches:
      - master
      - "releases/**"
    tags-ignore:
      - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches:
      - master
      - "releases/**"

permissions:
  contents: read
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        # At the time of writing macos-latest is mac 10; we need 11 to build a universal binary.
        os: [windows-latest]
        node: [16]
        runtime_link: [static, shared]
        use_global_liblzma: [true, false]
        enable_threads: [yes, no]
        exclude:
          # This OS does not have the ability to install liblzma globally
          - os: windows-latest
            use_global_liblzma: true
    runs-on: ${{ matrix.os }}
    name: Node ${{ matrix.node }} on ${{ matrix.os }} / System Xz ? ${{ matrix.use_global_liblzma }} / Threading enabled ? ${{ matrix.enable_threads }} / Runtime is ${{ matrix.runtime_link }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Use node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          architecture: x64
      - name: Install
        run: yarn install
        env:
          USE_GLOBAL: ${{ matrix.use_global_liblzma }}
          RUNTIME_LINK: ${{ matrix.runtime_link }}
          ENABLE_THREAD_SUPPORT: ${{ matrix.enable_threads }}
      - name: Test
        run: yarn test
