name: Test
on:
  push:
    branches:
      - master
      - "releases/**"
    tags-ignore:
      - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches:
      - master
      - "releases/**"

permissions:
  contents: read
jobs:
  test:
    strategy:
      matrix:
        # At the time of writing macos-latest is mac 10; we need 11 to build a universal binary.
        os: [ubuntu-latest, macos-11, windows-latest]
        node: [12, 14, 16]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} / Node ${{ matrix.node }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Use node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          architecture: x64
      - name: Install
        run: yarn install
      - name: Test
        run: yarn test
